import { useEffect,useState } from "react";
import { Link,useSearchParams } from "react-router-dom";
import PhysioLayout from "../../components/PhysioLayout/PhysioLayout";
import exerciseService from "../../services/exerciseService";
import physioPatientService from "../../services/physioPatientService";
import "./Exercises.css";

export default function Exercises(){
 const [params]=useSearchParams();const selected=params.get("id");const [library,setLibrary]=useState([]),[patients,setPatients]=useState([]),[patientId,setPatientId]=useState(selected||""),[assignments,setAssignments]=useState([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[error,setError]=useState("");const [form,setForm]=useState({exercise:"",frequency:"Daily",sets:3,reps:10,duration:"",instructions:""});
 const load=async()=>{try{setLoading(true);const [l,p]=await Promise.all([exerciseService.library(),physioPatientService.getPatients()]);setLibrary(l.exercises||[]);setPatients(p.patients||[]);if(selected){setPatientId(selected);const a=await exerciseService.assigned(selected);setAssignments(a.assignments||[])}}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[selected]);
 const assign=async()=>{if(!patientId||!form.exercise)return setError("Select a patient and exercise.");try{const d=await exerciseService.assign({...form,patient:patientId,sets:Number(form.sets),reps:Number(form.reps)});setAssignments(x=>[d.assignment,...x]);setMessage("Exercise assigned successfully.");}catch(e){setError(e.message)}};
 return <PhysioLayout><main className="wk-page"><header><div><span>EXERCISE LIBRARY</span><h1>Choose movement with purpose.</h1><p>Use the clinical library and assign a prescription directly to a patient.</p></div><Link to={patientId?`/physio/patient?id=${patientId}`:"/physio/patients"}>Patient workspace ↗</Link></header>
 <section className="wk-grid"><article><small>ASSIGN EXERCISE</small><h2>Patient prescription</h2><select value={patientId} onChange={async e=>{setPatientId(e.target.value);if(e.target.value){const d=await exerciseService.assigned(e.target.value);setAssignments(d.assignments||[])}}}><option value="">Choose patient</option>{patients.map(p=><option key={p._id} value={p._id}>{p.firstName} {p.lastName}</option>)}</select>
 <select value={form.exercise} onChange={e=>{const ex=library.find(x=>x._id===e.target.value);setForm({...form,exercise:e.target.value,sets:ex?.sets||3,reps:ex?.reps||10,duration:ex?.duration||""})}}><option value="">Choose exercise</option>{library.map(e=><option key={e._id} value={e._id}>{e.title} · {e.bodyArea||e.category}</option>)}</select>
 <div className="wk-form-row"><input type="number" min="1" value={form.sets} onChange={e=>setForm({...form,sets:e.target.value})}/><input type="number" min="1" value={form.reps} onChange={e=>setForm({...form,reps:e.target.value})}/><input placeholder="Duration" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></div>
 <input placeholder="Frequency e.g. Daily" value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}/><textarea placeholder="Patient-specific instructions" value={form.instructions} onChange={e=>setForm({...form,instructions:e.target.value})}/><button className="wk-primary" onClick={assign}>Assign exercise</button>{message&&<p className="wk-success">{message}</p>}{error&&<p className="wk-error">{error}</p>}</article>
 <aside><small>LIBRARY</small><strong>{library.length}</strong><span>Exercises available</span>{loading?<p>Loading library...</p>:library.map(e=><div className="wk-mini-row" key={e._id}><b>{e.category}</b><span>{e.title}</span><em>{e.difficulty}</em></div>)}</aside></section>
 <section className="wk-bottom"><article><small>ASSIGNED TO PATIENT</small><h2>{assignments.length} exercise{assignments.length===1?"":"s"}</h2>{assignments.map(a=><div className="wk-assignment" key={a._id}><strong>{a.exercise?.title}</strong><span>{a.sets} sets · {a.reps} reps · {a.frequency}</span><em>{a.status}</em></div>)}{!assignments.length&&<p>No exercises assigned yet.</p>}</article></section>
 </main></PhysioLayout>;
}
