import { Link } from "react-router-dom";
import Navbar from "../../../components/Navbar/Navbar";
import Footer from "../../../components/Footer/Footer";
import "./ShoulderRehabilitation.css";
import "../../fitmax-premium.css";


function ShoulderRehabilitation() {
  return <div className="condition-page">
    <Navbar />
    <main>
      <section className="condition-hero"><div className="condition-container condition-hero-grid">
        <div><div className="condition-eyebrow"><span className="condition-mark"><span/><span/><span/></span><span>SHOULDER REHABILITATION</span></div>
          <h1>Build stronger,<span>more confident movement.</span></h1>
          <p className="condition-hero-copy">Personalized rehabilitation to help improve shoulder movement, strength and function after pain, injury or reduced activity.</p>
          <div className="condition-actions"><Link to="/book-assessment" className="condition-btn primary">Start Your Recovery <span>↗</span></Link><Link to="/book-assessment" className="condition-btn secondary">Book an Assessment</Link></div>
          <div className="condition-meta"><span>01 Assessment</span><span>02 Rehabilitation</span><span>03 Progress</span></div>
        </div>
        <div className="condition-hero-image"><img src="https://images.pexels.com/photos/6111616/pexels-photo-6111616.jpeg?auto=compress&cs=tinysrgb&w=1600" alt="Physiotherapy and rehabilitation"/><div className="condition-overlay"/><div className="condition-floating"><span>FITMAX / RECOVERY</span><strong>Assess.<br/>Rebuild.<br/>Return.</strong></div></div>
      </div></section>

      <section className="condition-intro"><div className="condition-container"><div className="condition-intro-top"><div className="condition-label"><span>01</span><strong>UNDERSTANDING YOUR RECOVERY</strong></div><div className="condition-line"/></div>
        <div className="condition-intro-grid"><h2>Your recovery is <span>personal.</span></h2><div><p>Personalized rehabilitation to help improve shoulder movement, strength and function after pain, injury or reduced activity.</p><p>FitMax focuses on where you are now, what you want to improve and the everyday activities you want to return to.</p></div></div>
      </div></section>

      <section className="condition-support"><div className="condition-container"><div className="condition-heading"><div><div className="condition-eyebrow"><span className="condition-mark"><span/><span/><span/></span><span>WHO WE CAN HELP</span></div><h2>Different needs.<span>One clear direction.</span></h2></div><p>Explore the areas where structured physiotherapy and rehabilitation may support your recovery.</p></div><div className="condition-grid"><div className="condition-card"><span>01</span><h3>Shoulder Pain</h3><p>Personalized rehabilitation based on your condition, current abilities and recovery goals.</p><i>↗</i></div>
<div className="condition-card"><span>02</span><h3>Reduced Mobility</h3><p>Personalized rehabilitation based on your condition, current abilities and recovery goals.</p><i>↗</i></div>
<div className="condition-card"><span>03</span><h3>Shoulder Weakness</h3><p>Personalized rehabilitation based on your condition, current abilities and recovery goals.</p><i>↗</i></div>
<div className="condition-card"><span>04</span><h3>Post Injury Recovery</h3><p>Personalized rehabilitation based on your condition, current abilities and recovery goals.</p><i>↗</i></div></div></div></section>

      <section className="condition-help"><div className="condition-container condition-help-grid"><div className="condition-help-image"><img src="https://images.pexels.com/photos/7659562/pexels-photo-7659562.jpeg?auto=compress&cs=tinysrgb&w=1500" alt="Physiotherapist helping patient"/><div className="condition-overlay"/><div className="condition-help-badge"><span>FITMAX APPROACH</span><strong>Recovery is a<br/>process, not a moment.</strong></div></div><div><div className="condition-eyebrow"><span className="condition-mark"><span/><span/><span/></span><span>HOW FITMAX HELPS</span></div><h2>Build towards <span>better function.</span></h2><p className="condition-help-copy">Your rehabilitation can be shaped around your current abilities, goals and progress. The focus is on helping you move forward with professional guidance.</p><div className="condition-help-points"><div><span>01</span><div><strong>Understand your starting point</strong><p>Begin with your condition, movement, symptoms and goals.</p></div></div><div><span>02</span><div><strong>Follow guided rehabilitation</strong><p>Progress through exercises and movement suited to your recovery stage.</p></div></div><div><span>03</span><div><strong>Track your progress</strong><p>Review how your movement, strength and confidence are changing.</p></div></div><div><span>04</span><div><strong>Work towards your goals</strong><p>Build towards everyday activities and independence.</p></div></div></div></div></div></section>

      <section className="condition-journey"><div className="condition-container"><div className="condition-heading"><div><div className="condition-eyebrow"><span className="condition-mark"><span/><span/><span/></span><span>YOUR RECOVERY JOURNEY</span></div><h2>Five stages.<span>One direction.</span></h2></div><p>Each stage builds towards the next, helping you move from understanding your condition to returning to life.</p></div><div className="condition-journey-grid"><div className="condition-step"><div className="condition-step-number">01</div><div className="condition-step-content"><h3>Assessment</h3><p>Understand your current movement, symptoms and goals.</p></div><i>→</i></div><div className="condition-step"><div className="condition-step-number">02</div><div className="condition-step-content"><h3>Personalized Plan</h3><p>Build a rehabilitation direction around your needs.</p></div><i>→</i></div><div className="condition-step"><div className="condition-step-number">03</div><div className="condition-step-content"><h3>Guided Rehab</h3><p>Progress through structured exercises and movement.</p></div><i>→</i></div><div className="condition-step"><div className="condition-step-number">04</div><div className="condition-step-content"><h3>Track Progress</h3><p>Review how your abilities and confidence are changing.</p></div><i>→</i></div><div className="condition-step"><div className="condition-step-number">05</div><div className="condition-step-content"><h3>Return to Life</h3><p>Work towards the activities and routine that matter to you.</p></div></div></div></div></section>

      <section className="condition-life"><div className="condition-container condition-life-grid"><div><div className="condition-eyebrow"><span className="condition-mark"><span/><span/><span/></span><span>BACK TO WHAT MATTERS</span></div><h2>Recovery should <span>change your everyday.</span></h2><p className="condition-help-copy">The goal is not simply to complete exercises. It is to help you feel more capable in the things you need and want to do.</p><div className="condition-life-list"><div><span>01</span><strong>Move with more confidence</strong></div><div><span>02</span><strong>Build strength and control</strong></div><div><span>03</span><strong>Return to your routine</strong></div><div><span>04</span><strong>Work towards independence</strong></div></div></div><div className="condition-life-visual"><div className="condition-circle"><div><span>FITMAX</span><strong>MOVE</strong><small>BUILD</small><small>RETURN</small></div></div><div className="condition-orbit one"/><div className="condition-orbit two"/></div></div></section>

      <section className="condition-safety"><div className="condition-container"><div className="condition-safety-box"><div className="condition-safety-icon">+</div><div><span>YOUR SAFETY MATTERS</span><h3>Rehabilitation should be <strong>appropriate for you.</strong></h3><p>Physiotherapy should be tailored to your individual situation. If your symptoms require an in person examination or medical evaluation, your care team can guide you towards the appropriate next step.</p></div></div></div></section>

      <section className="condition-cta"><div className="condition-cta-image"><img src="https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=1800" alt="Patient receiving physiotherapy"/></div><div className="condition-cta-overlay"/><div className="condition-container condition-cta-content"><div className="condition-eyebrow condition-light"><span className="condition-mark"><span/><span/><span/></span><span>READY TO START?</span></div><h2>Take the next step <span>towards recovery.</span></h2><p>Start with an assessment and take the first step towards a rehabilitation journey built around you.</p><Link to="/book-assessment" className="condition-btn primary">Book an Assessment <span>↗</span></Link></div></section>
    </main>
    <Footer />
  </div>;
}
export default ShoulderRehabilitation;
